ChatTestWeb/Models/ErrorViewModel.cs
namespace ChatTestWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ChatTestWeb/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;
using Infra.Helper;
using Data.Models;

namespace ChatTestWeb.Controllers
{
    public class ChatController : Controller
    {
        public IActionResult ChatView()
        {
            return View();
        }

        public IActionResult _chatlist()
        {
            return PartialView("_chatlist");
        }

        public async Task<IActionResult> _userlist(int id)
        {
            var users = await UserRequestHelper.GetAllUserExcept(id);
            return PartialView("_userlist", users);
        }

        public async Task<IActionResult> IdentifyUser(string username)
        {
            var user = await UserRequestHelper.GetUserByUsername(username);
            if (user == null)
            {
                return NotFound();
            }
            return Ok(user);
        }

        public async Task<IActionResult> GetSpecificChatData(int fromuserid, int touserid)
        {
            var chatdata = await ChatRequestHelper.GetSpecificChatData(fromuserid, touserid);
            return Ok(chatdata);
        }

        public async Task<IActionResult> InsertChatData(string message, int fromuserid, int touserid)
        {
            var chatdata = await ChatRequestHelper.InsertChatData(message, fromuserid, touserid);
            return Ok(chatdata);
        }

        public async Task<IActionResult> InsertChat(tbChat chat)
        {
            var data = await ChatRequestHelper.InsertChat(chat);
            return Ok(data);
        }
	}
}

ChatTestWeb/Controllers/HomeController.cs
using System.Diagnostics;
using ChatTestWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace ChatTestWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ChatTestWeb/Views/Chat/ChatView.cshtml
<div id="userlist">
	
</div>

<div class="mt-3">
	<div id="chatlist"></div>
</div>


@section scripts{
	<script>
		"use strict";


		var connection = new signalR.HubConnectionBuilder().withUrl("https://localhost:7200/chathub").build();

		connection.start().then(function () {

		}).catch(function (err) {
			console.log(err)
		})

		let sendToUserId = null;
		let currentUserId = parseInt(localStorage.getItem("userid"));


		function UserIdentifier(){
			const getUsername = localStorage.getItem("username");
			const getUserId = localStorage.getItem("userid");
			if(getUsername == null || getUserId == null){
				let username = prompt("Please State Your Identifier");
				$.ajax({
					cache: false,
					url: '@Url.Action("IdentifyUser", "Chat")',
					data: {username},
					beforeSend: function(){

					},
					success: function(response){
						if(response != null){
							localStorage.setItem("username", username);
							localStorage.setItem("userid", response.id);
						}
					},
					error: function(error){
						console.log(error);
					}
				})
			}else{
				return;
			}
		}

		$(function(){
			UserIdentifier();
			CallUserListPartial();
		})

		function CallUserListPartial(){
			const id = localStorage.getItem("userid");
			$.ajax({
				cache: false,
				url: '@Url.Action("_userlist", "Chat")',
				data: {id},
				type: "GET",
				success: function(response){
					$("#userlist").empty().append(response);
					$("button").click(function() {
						let touserid = parseInt(this.id);
						sendToUserId = parseInt(this.id);
						const fromuserid = localStorage.getItem("userid");
						CallChatListPartial(fromuserid, sendToUserId)
					});
				},
				error: function(error){
					console.log(error)
				}
			})
		}

		function CallChatListPartial(fromuserid, touserid){
			
			$.ajax({
				cache: false,
				url: '@Url.Action("_chatlist", "Chat")',
				beforeSend: function () {

				},
				success: function (response) {
					$("#chatlist").empty().append(response);
					$.ajax({
						cache: false,
						url: '@Url.Action("GetSpecificChatData", "Chat")',
						data: {fromuserid, touserid},
						type: "GET",
						beforeSend: function(){

						},
						success: function(response){
							let getUserid = parseInt(localStorage.getItem("userid"));
							console.log(response)
							var robotImageUrl = 'https://s3-us-west-2.amazonaws.com/chrisnielsen/robot.png';
							// Cartoon vector designed by Freepik
							// http://www.freepik.com/free-photos-vectors/cartoon
							// Pre-load image
							$('<img/>')[0].src = robotImageUrl;
							response.forEach((data) => {
								if (data.fromUserId === getUserid) {
									addToLog(data.message, true);
								}else{
									addToLog(data.message, false);
								}
							})
							$("#fromUserId").val(currentUserId);
							$("#toUserId").val(sendToUserId);
							connection.on("SendMessage", function (message, fromUserId, toUserId) {
								if (fromUserId === currentUserId) {
									addToLog(message, true);
								}
								if (currentUserId === toUserId) {
									addToLog(message, false);
								}
							})
							$('#messageForm').submit(function (event) {
								event.preventDefault();
								//var fromuserid = currentUserId;
								//var touserid = sendToUserId;
								//var $userInput = $(this).find('#message');
								var userinput = document.getElementById("message");
								
								$.ajax({
									cache: false,
									url: '@Url.Action("InsertChat", "Chat")',
									type: "GET",
									data: $(this).serialize(),
									beforeSend: function () {
									},
									success: function (data) {
										var message = userinput.value;
										connection.invoke('SendMessage', message, currentUserId, sendToUserId).catch(function (error) {
											console.log(error);
										})
										//$userInput.val('');
										userinput.value = ""
									},
									complete: function () {
										
									},
									error: function (error) {
										console.log(error);
									}
								})
							});
							

							function addToLog(message, user) {
								var $message = $('<div class="message animated"></div>');

								if (!user) {
									var $picture = $('<img src="' + robotImageUrl + '"></img>');
									$message.append($picture);
								}

								var $content = $('<div class="content"></div>');
								$content.html(message);
								$message.append($content);

								var $log = $('.log');
								$log.append($message);

								if (user) {
									$message.addClass('user');
								}

								$log.animate({ scrollTop: $log[0].scrollHeight }, "slow", 'linear');

								setTimeout(function () {
									if (user) {
										$message.addClass('user');
										$message.addClass('fadeInRightBig');
									} else {
										$message.addClass('fadeInLeftBig');
									}
								}, 0);
							}
						},
						complete: function(){
							
						},
						error: function(error){
							console.log(error)
						}
					})
					
				},
				error: function (error) {
					console.log(error);
				}
			})
		}
		
	</script>
}

ChatTestWeb/Views/Chat/_chatlist.cshtml
@model Data.Models.tbChat

<style>
    * {
        font-family: 'Raleway', sans-serif;
    }

    html, body {
        height: 100%;
    }

    .chat-log {
        position: relative;
        align-content: center;
        align-items: center;
        width: 100%;
        max-width: 600px;
        height: 90%;
        border: 1px solid #f7f7f7;
    }

    .log {
        height: calc(100% - 50px);
        overflow-y: auto;
    }

    .input {
        background-color: #F7F7F7;
        height: 50px;
    }

    .user-input {
        color: #B4B7BF;
        background-color: transparent;
        width: calc(100% - 90px);
        border: 0px;
        font-size: 1.1em;
        line-height: 50px;
        margin-left: 20px;
        outline: none;
    }

    button {
        color: #B4B7BF;
        background-color: transparent;
        border: 0px;
        width: 60px;
        padding: 14px;
        outline: none;
        display: inline-block;
        cursor: pointer;
    }

    .message {
        margin: 20px;
        font-size: 1em;
        opacity: 1;
        float: left;
        clear: both;
    }

        .message.user {
            float: right;
            clear: both;
        }

        .message img {
            width: 50px;
            float: left;
        }

    .content {
        background: #8DABE3;
        color: #ffffff;
        padding: 15px;
        border-radius: 5px;
        float: left;
        margin-left: 15px;
    }

    .user .content {
        color: #868995;
        background: #f7f7f7;
        max-width: none;
    }


    .credit {
        margin-top: 20px;
    }
</style>

<div class="chat-log">
    <div class="log">
    </div>
    <div class="input">
        <form id="messageForm">
            <input type="hidden" name="fromUserId" asp-for="fromUserId" id="fromUserId" />
            <input type="hidden" name="toUserId" asp-for="toUserId" id="toUserId" />
            <input type="text" class="user-input" placeholder="message..." asp-for="message" name="message" id="message" />
            <button>
                <i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i>
            </button>
        </form>
    </div>
</div>

ChatTestWeb/Views/Chat/_userlist.cshtml
@model IEnumerable<Data.Models.tbUser>

<style>
	.users{
		position: relative;
		display: flex;
	}
</style>

<div class="users">
	@foreach(var user in Model){
		<div>
			<button type="button" class="btn btn-info" style="margin-left: 10px;" id="@user.id">@user.username</button>
		</div>
	}
</div>

ChatTestWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ChatTestWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChatTestWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChatTestWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChatTestWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ChatTestWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/signalr/dist/browser/signalr.js" asp-append-version="true"></script>
    <script src="~/js/Chat.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>